# rodney: rodrigolive fork of simonw/rodney. Run `make` for help.

VERSION     ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS     := -s -w -X main.version=$(VERSION)
INSTALL_DIR ?= $(HOME)/util
UPSTREAM    ?= upstream
ARGS        ?= --help
TAG         ?=
NOTES       ?=
# 'make release' publishes where it checks HEAD: origin, never an override
override REPO := $(shell git remote get-url origin 2>/dev/null | sed -E 's,^.*github\.com[:/],,; s,\.git$$,,')

.DEFAULT_GOAL := help
.PHONY: help build vet test test-sh run install release upstream clean

help: ## Show this help
	@echo "rodney $(VERSION): Chrome automation CLI (rodrigolive fork of simonw/rodney)"
	@echo
	@echo "Usage: make <target> [VAR=value]"
	@echo
	@echo "Targets:"
	@awk 'BEGIN {FS = ":.*## "} /^[a-z][a-z-]*:.*## / {printf "  %-10s %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@echo
	@echo "Variables:"
	@echo "  VERSION      stamped into the binary (default: git describe, now $(VERSION))"
	@echo "  INSTALL_DIR  where 'make install' puts the binary (default: $(INSTALL_DIR))"
	@echo "  UPSTREAM     git remote for simonw/rodney (default: $(UPSTREAM))"
	@echo "  ARGS         arguments for 'make run' (default: $(ARGS))"
	@echo "  TAG          release tag for 'make release', always rod-vX.Y.Z (upstream owns vX.Y.Z)"
	@echo "  NOTES        release notes file for 'make release' (default: generated by GitHub)"
	@echo "               'make release' publishes to origin's GitHub repo (now $(REPO))"
	@echo
	@echo "Examples:"
	@echo "  make build && ./rodney version"
	@echo "  make run ARGS='open https://example.com'"
	@echo "  make install              # vet + build, then copy to $(INSTALL_DIR)/rodney"
	@echo "  make release TAG=rod-v0.5.1 NOTES=notes.md  # CI attaches macOS/Linux binaries"
	@echo "  make upstream             # list simonw/rodney commits not merged here yet"
	@echo
	@echo "Tests boot a real headless Chrome; rod downloads Chromium unless ROD_CHROME_BIN is set."

build: ## Build ./rodney with the git version stamped in
	go build -trimpath -ldflags="$(LDFLAGS)" -o rodney .

vet: ## go vet, gofmt check, and compile the tests without running them
	go vet ./...
	@out=$$(gofmt -l .); if [ -n "$$out" ]; then echo "gofmt needed:"; echo "$$out"; exit 1; fi
	go test -c -o /dev/null .

test: ## Full Go test suite (boots one headless Chrome)
	go test ./... -count=1

test-sh: build ## Bash integration harness (./test.sh) in a throwaway RODNEY_HOME
	go build -o /tmp/testserver ./tests/testserver
	RODNEY_HOME=$$(mktemp -d) bash ./test.sh

run: ## Run from source: make run ARGS='open https://example.com'
	go run . $(ARGS)

install: vet build ## Copy the built binary to INSTALL_DIR
	install -m 0755 rodney $(INSTALL_DIR)/rodney
	@echo "installed rodney $(VERSION) -> $(INSTALL_DIR)/rodney"

release: ## Publish a GitHub release of pushed HEAD: make release TAG=rod-vX.Y.Z [NOTES=file]
	@printf '%s\n' "$(TAG)" | grep -Eqx 'rod-v[0-9]+\.[0-9]+\.[0-9]+' || { echo "usage: make release TAG=rod-vX.Y.Z [NOTES=file]"; exit 1; }
	@test -z "$$(git status --porcelain --untracked-files=no)" || { echo "uncommitted changes: commit and push first"; exit 1; }
	@git fetch -q origin main
	@test "$$(git rev-parse HEAD)" = "$$(git rev-parse origin/main)" || { echo "HEAD is not origin/main: push first"; exit 1; }
	gh release create "$(TAG)" -R "$(REPO)" --target "$$(git rev-parse HEAD)" --title "$(TAG)" \
		$(if $(NOTES),--notes-file "$(NOTES)",--generate-notes)
	git fetch -q --tags origin
	@echo "publish.yml is now building and attaching the binaries: gh run list -R $(REPO) -w Publish"

upstream: ## Fetch simonw/rodney and list commits not merged here
	git fetch $(UPSTREAM)
	@git log --oneline HEAD..$(UPSTREAM)/main || true

clean: ## Remove build outputs
	rm -f rodney rodney-*
